### ISSUE TITLE
Feature: uceprotect lists

### ISSUE THREAD

**Issue by KristijanL** [maravento/blackip#1]
Hi,

would you consider adding uceprotect.net black lists?

Best Regards,
Kristijan

**Comment by maravento** [comment]
Can you post the direct link to the list to verify it?

**Comment by KristijanL** [comment]
Hi,

you can use different  methods of obtaining the lists
WGET: 
- Level 1: http://wget-mirrors.uceprotect.net/rbldnsd-all/dnsbl-1.uceprotect.net.gz
- Level 2: http://wget-mirrors.uceprotect.net/rbldnsd-all/dnsbl-2.uceprotect.net.gz
- Level 3: http://wget-mirrors.uceprotect.net/rbldnsd-all/dnsbl-3.uceprotect.net.gz

RSYNC:
http://www.uceprotect.net/en/index.php?m=6&s=10

info on Levels:
http://www.uceprotect.net/en/index.php?m=3&s=3
http://www.uceprotect.net/en/index.php?m=3&s=4
http://www.uceprotect.net/en/index.php?m=3&s=5

Best Regards,
Kristijan

**Comment by maravento** [comment]
Done... Included in the last commit. Thanks for your contribution
