### ISSUE TITLE
The list is too big.

### ISSUE THREAD

**Issue by oantonioo** [maravento/blackip#3]
The list is too big.
It would be great to have it divided into files differentiated by the type of attack of each IP or to have a smaller version that only includes the most annoying IPs.

This list solves a lot of my spam problem but http calls have become very slow.
Could you recommend a smaller list of spammer IPs?

Thank you

Edit a few minutes later.

Looking for a way to reduce the list, I already eliminated more than 1000 ips in a few minutes.
I discovered something strange in the temporary file.
/tmp/ipset_blackip.txt

add chain_DENY 189.203.56.107
add chain_DENY 189.203.56.165
add chain_DENY 189.203.56.157
add chain_DENY 189.203.56.158
add chain_DENY 189.203.56.57
add chain_DENY 189.203.56.38
add chain_DENY 189.203.56.85
add chain_DENY 189.203.56.86
add chain_DENY 189.203.56.186
add chain_DENY 189.203.56.41
add chain_DENY 189.203.56.64
add chain_DENY 189.203.56.24
add chain_DENY 189.203.56.0/24

**after adding a dozen IPs do you add the entire block?
I do not see it much sense**

**Comment by maravento** [comment]
Assuming your ipset is v8.32 or higher:

Referring to: "**the list is too big**":
As clearly explained in "[Important about Ipset/Iptables Rules](https://github.com/maravento/blackip#important-about-ipsetiptables-rules)", the size of the list is determined by the parameter `maxelem 10000000`, **which for `blackip.txt` is more than enough**. 
It is important to note that `blackip.txt` is debugged. The sources are public, and you can consult them in [README/BLOCKLIST](https://github.com/maravento/blackip#blocklists). So, if you remove IP addresses from `blackip.txt`, you would be excluding IP addresses marked on public blacklists. Therefore, it is an action that we do not recommend.

Perform the following test to verify that you are doing the described procedure correctly:

**First - clean blackip set**  
open the command terminal (shell) and run:
```
sudo iptables -F
sudo iptables -X
sudo ipset flush blackip
sudo ipset -L blackip
```
And the output should appear with `Number of entries: 0`:
![set_blackip](https://user-images.githubusercontent.com/14880802/207066711-38ba004d-1d8b-4204-a87a-8684c24963a0.png)

**Second - create a bash**
```
sudo touch test.sh
sudo chmod +x test.sh
```
Put `blackip.txt` in the same path as `test.sh` script. run `ls` command:
```
ls
blackip.txt  test.sh
```
**Third - add `blackip.txt` to set `blackip`**
Edit the `test.sh` script and add the following content:

There are two ways to do it:
1. The first one is already published in the [Ipset/Iptables Rules](https://github.com/maravento/blackip#ipsetiptables-rules) section (faster). In short: 
```
#!/bin/bash
cat blackip.txt | sort -V -u | while read line; do
    echo "add blackip $line" >> ipset_blackip.txt
done
ipset -! restore < ipset_blackip.txt
```
2. add the IP addresses from `blackip.txt`, one by one (very slow)
```
#!/bin/bash
for ip in $(cat blackip.txt | sort -V -u); do
     ipset -! add blackip "$ip"
done
```
**You must choose between only one of the two methods and run the script (and be patient and wait for it to finish):**
```
sudo ./test.sh
```
Upon completion of the script execution, verify that the IP addresses from the `blackip.txt` file were correctly added to the ipset blackip set:
```
sudo ipset -L blackip
```
And the final step would be to block the set with iptables (iptables rules described in README)
