### ISSUE TITLE
Please add ELLIO: IP Feed (Community version) to the feeds. 

### ISSUE THREAD

**Issue by elliotechayush** [maravento/blackip#5]
Hi, thank you for this amazing aggregated list.
Here is another link that can be a part of this feed.
[](https://cdn.ellio.tech/community-feed).
Thank You.

**Comment by elliotechayush** [comment]
I don't know where did the link go.
Sorry for that.
https://cdn.ellio.tech/community-feed

**Comment by maravento** [comment]
Added list [Update 09/12/2023](https://github.com/maravento/blackip/commit/32711fd2f0dda8b9ebf6dd7764732f450a37cd56#diff-d2744556b77e2054f61dc50cbe2f4be26bf88bc6dfbc12223336ed57b79def22R91)
Thanks for the contribution
